<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MyProject.DAL\MyProject.DAL.csproj" />
    <ProjectReference Include="..\MyProject.DTO\MyProject.DTO.csproj" />
  </ItemGroup>

</Project>
